### ISSUE TITLE
Minor typo on website

### ISSUE THREAD

**Issue by keck-in-space** [nimble-code/Cobra#11]
http://spinroot.com/cobra/downloads.html

Has a typo: "Cobra is be available starting on Github at github.com/nimble-code/Cobra."

**Comment by nimble-code** [comment]
thanks! fixed

**Comment by keck-in-space** [comment]
I still see the typo there.

I believe "Cobra is be available starting on Github at github.com/nimble-code/Cobra." maybe should be "Cobra is available on Github at github.com/nimble-code/Cobra."

**Comment by nimble-code** [comment]
sigh -- ok, fixed some more, i think :-)

**Comment by keck-in-space** [comment]
Looks great to me! Thank you. :)
