### ISSUE TITLE
Better JSON output

### ISSUE THREAD

**Issue by pigsinablanket** [nimble-code/Cobra#13]
In the JSON output when using the `-json` flag, there are a couple issues
* Remove trailing commas on the `"line"` field:
```
 [
  { "type"	:	"/define @ident \( .* x:@ident .* \) [. (]* ^\( :x",
    "message"	:	"lines 20..22",
    "file"	:	"dynamic/pam.c",
    "line"	:	20,
  },
  { "type"	:	"/define @ident \( .* x:@ident .* \) [. (]* ^\( :x",
    "message"	:	"lines 19..19",
    "file"	:	"libpam/pam_env.c",
    "line"	:	19,
  }
]
```
* Don't escape characters in `"type"` field as it produces invalid JSON. The only characters that should be escaped should be double quotes and backslashes
* When there is no match for a pattern, I would expect the empty array `[]`, instead I get:
```
[
  { "type"	:	"/restore \( .* \) { .* }",
    "message"	:	"no matches found",
    "file"	:	"stdin",
    "line"	:	0,
  }
]
```

**Comment by nimble-code** [comment]
thanks for pointing this out. will fix in the next update.

**Comment by nimble-code** [comment]
just updated the sources to fix this.
also added a json+ option to output a little more information per match
(e.g., including the names of bound variables, if any, and the first line of
a code fragment that is matched).  this works both as a commandline
flag -json or -json+ and as an interactive command json or json_
