### ISSUE TITLE
Warnings don't go to stderr

### ISSUE THREAD

**Issue by pigsinablanket** [nimble-code/Cobra#14]
I get a warning for a pattern expression that goes to stdout which causes issues with parsing
```
$ cobra -json -pe "{ .* memset ( ^)* x:@ident , ^)* , ^)* ) ^:x* free ( ^):x ) .* }" a.c
warning: is a space missing before : in '):x'?
```
This specific warning is also a false positive.

**Comment by nimble-code** [comment]
hi - the warning is actually accurate -- the final ^):x fragment in the expression should be written ^)  :x  or else the parser will try to look for anything other (the ^) than the single three-letter token ):x
but, yes, it should go to stderr -- will fix that.  (also working on fixes for the other two issues -- will have that ready soon)

**Comment by nimble-code** [comment]
actually, the warning is already going to stderr (line 1902 in the current cobra_te.c on github)

**Comment by pigsinablanket** [comment]
Thank you for the clarification for the warning.

It looks like it was changed very recently and I hadn't pulled down the latest changes.
