### ISSUE TITLE
Invalid match

### ISSUE THREAD

**Issue by TomMD** [nimble-code/Cobra#15]
Call:

```
# cobra -recursive "x.c" -json -pe "^struct . { .* @type x:@ident ^:x* }"
```

Code:

```
typedef struct lprint_dymo_s            // DYMO driver data
{
  unsigned      ystart,                 // First line
                yend;                   // Last line
  int           feed;                   // Accumulated feed
} lprint_dymo_t;
```

Result:

```
[
  { "type"      :       "^struct . { .* @type x:@ident ^:x* }",
    "message"   :       "lines 1..6",
    "file"      :       "./x.c",
    "line"      :       1
  }
]
```

Real world occurrence: https://github.com/michaelrsweet/lprint/pull/35

Some toying shows that the comment ruins the match.  If we delete the comment on the `typedef struct ...` line then the false match goes away.

**Comment by nimble-code** [comment]
there are several ways to avoid the problem.  
one is to use, instead of the dot . after ^struct to say: ^{*
which then moves forward over the comment.  
another method is to explicitly allow for one or more comments with: ^struct . @cmt* { .... etc.
an a third is to run the preprocessor (but that requires knowing the required compilation directives of course)

**Comment by TomMD** [comment]
Ahh, comment is a token we can match and need to interleave in all the patterns.  Thank you!

**Comment by TomMD** [comment]
Is there any setting to just drop/filter comments from the stream so we don't need to make every pattern `tok1 @cmt* tok2 @cmt* tok3 ...`?

**Comment by nimble-code** [comment]
that's a thought.  there's none yet, though such a filter could be written as a script too.
maybe I'll add a command line option to do this
should that also omit compiler directives though? (a #define could also appear anywhere, although
that would be less common than a comment)

**Comment by nimble-code** [comment]
I'll ad the option in the next update though

**Comment by nimble-code** [comment]
I've updated the sources and changed the working of command-line option -comments to do what you needed.
by default now, comments are not part of the token stream (which does make more sense).  they can be included
with command-line option -comments.  of course, if preprocessing is used (-cpp) then comments are gone anyway,
so using both -cpp and -comments isn't useful and triggers a warning.
similarly, if one uses @cmnt in queries and -comments was not set, a warning will be given (once).
also added a file with useful sample pattern expressions under rules/main/patterns.cobra
plus various other improvements in accuracy
thanks for the feedback -- this does make it simpler to write and find code patterns
