### ISSUE TITLE
Segmentation fault in 3.5 but not in 3.1

### ISSUE THREAD

**Issue by keck-in-space** [nimble-code/Cobra#16]
Hello,

I am seeing a Segmentation fault (core dumped) error in Cobra 3.5 that isn't present in 3.1.

This only occurs for two rulesets -- MISRA 1997 and MISRA 2004.

_misra1997_
```
:m97_rule82
eval: '(.txt != } || .curly > 1)'
:m97_rule83
Segmentation fault (core dumped)
```

_misra2004_
```
:m04_rule16.5
:m04_rule16.8
Segmentation fault (core dumped)
```

The other included rulesets run without issue.

**Comment by nimble-code** [comment]
thanks for reporting.  will check it and fix

**Comment by nimble-code** [comment]
fixed
