### ISSUE TITLE
Infinite loop in CWE rule definition 

### ISSUE THREAD

**Issue by bauer-matthews** [nimble-code/Cobra#17]
Running the command `cobra -comments -f cwe <filename>`  where `<filename>` has the contents:

```c
#include <stdlib.h>

void func()
{
    void *a=malloc(1);
    if(NULL != a) {
        memset(a, 0, 1);
        free(a);
    }
}
````

results in an infinite loop. Problematic rule seems to be `cwe_416.cobra`. This applies to revision ab06e676f9123ec07011a09c38daffaa4fbfdc60.

**Comment by nimble-code** [comment]
that's bad -- I'll check it out.  thanks for showing a short example for this.

**Comment by nimble-code** [comment]
thanks for catching this.  it was indeed a problem in cwe_416.cobra -- now updated and fixed
