### ISSUE TITLE
False positive: "Inconsistent checks of function return values"

### ISSUE THREAD

**Issue by mjeronimo** [nimble-code/Cobra#22]
In C++ files, using "extern C {" causes some rules to fire when they shouldn't, such as the "Inconsistent checks of function return values" in the Basic rule set. The rule seems to be interpreting the function definition as an invocation, probably because of the opening brace in the "extern C". 

To reproduce:

`$ cobra -C++ -f basic -comments t1.c
`

Input file:

```
#ifdef __cplusplus
extern "C"
{
#endif

bool
rcl_node_is_valid(const rcl_node_t * node)
{
  bool result = rcl_node_is_valid_except_context(node);
  if (!result) {
    return result;
  }
  if (!rcl_context_is_valid(node->context)) {
    RCL_SET_ERROR_MSG("rcl node's context is invalid");
    return false;
  }
  return true;
}

rcl_node_get_options(const rcl_node_t * node)
{
  if (!rcl_node_is_valid(node)) {
    return NULL;  // error already set
  }
  return &node->impl->options;
}

#ifdef __cplusplus
}
#endif
```

Results in:

```
=== Inconsistent checks of function return values:
 1: rcl_node_is_valid checked 1 times out of 2
```

**Comment by nimble-code** [comment]
updated rules/main/basic.def to prevent the confusion in this case
(added a check to reveal if the name matched is part of a function definition rather than a function call)
