### ISSUE TITLE
False positive: "deref of <x> preceds null test"

### ISSUE THREAD

**Issue by mjeronimo** [nimble-code/Cobra#27]
Using the basic ruleset, when a pointer variable is initialized in a declaration list, the rule incorrectly identifies it as a dereference, which results in the "deref preceeds null test" warning. 

To reproduce:

`$ cobra -C++ -comments -f basic t.c`

Where t.c is:

```
char *
rcutils_repl_str(
  const char * str,
  const char * from,
  const char * to,
  const rcutils_allocator_t * allocator)
{
  char *pret, *ret = NULL;

  if (ret == NULL) {
    ;
  }

  return ret;
}
```

Results:

```
t.c:8 	deref of ret 	preceeds null test at line 10
Candidate reverse nulls: 2
t.c:8:
  1:      8    char *pret, *ret = NULL;
t.c:10:
  2:     10    if (ret == NULL) {
1 errors
```

**Comment by nimble-code** [comment]
reverse null rule updated to remove this false positive
thanks for reporting!
