### ISSUE TITLE
"cobra -configure $COBRA/rules" sets wrong folder for rules

### ISSUE THREAD

**Issue by yilmazdurmaz** [nimble-code/Cobra#31]
I have made a docker alpine-based image to work with cobra and compile it from source code.

I have hit the following problem.

````
$ export COBRA=/workspace/cobra
$ cobra -configure $COBRA/rules

> cobra: configuration completed

$ cobra -cpp -f basic *.[ch]

> cobra: cannot find 'basic'
````

I have checked the `~/.cobra ` and found out the configure command adds an extra "/rules" to the path

````
$ cat ~/.cobra 

> Rules: /workspace/cobra/rules/rules
> # ncore: 1
````

---

Opposed to what is in the README file, using only `cobra -configure $COBRA` solves the problem.

Please fix this either in the configuration method or in the README file.

---
PS: I don't know of your standing point for using docker. If you are positive and just did not have time for that, I can supply my dockerfile.

**Comment by nimble-code** [comment]
fixed!  thanks for catching this.
thanks for offering to share the dockerfile
not ready for it, but may take you up on it at some point
thanks
