### ISSUE TITLE
setting `$C_BASE` in `.profile` gives a weird error

### ISSUE THREAD

**Issue by yilmazdurmaz** [nimble-code/Cobra#32]
I try to set rules folder through `$C_BASE`. But get a weird problem.

Any idea this relates to the program itself?

The problem is as follows:

Download Cobra and set the path along with these two in `.profile` file (it is an AWS machine)
````
echo COBRA='~/workspace/Cobra' >> ~/.profile
echo C_BASE='$COBRA/rules' >> ~/.profile
exit
````

Log in again and check if `$C_BASE` is set after login with `echo $C_BASE`.
````
/home/ubuntu/workspace/Cobra/rules
````
It seems correctly set but the following error says otherwise. Go to the Cobra folder and issue the command `cobra -terse -comments -f basic src/cobra_links.c`. 
````
error: cannot open ~/.cobra : check tool installation
cobra: cannot find 'basic'
````

Set it exactly same again, but with `export` in the console. 
````
export C_BASE=$COBRA/rules
echo $C_BASE
/home/ubuntu/workspace/Cobra/rules
````

`$C_BASE` seemingly has exactly the same value, alas it is working now.
````
cobra -terse -comments -f basic src/cobra_links.c
=== Fct names also used as variables: 4
=== Modifying the control variable of a for loop inside the loop body: 1
=== Missing else at end of if-else-if chain: 4
=== Missing default in switch statement: 3
=== Functions defined more than once: 0
````

**Comment by nimble-code** [comment]
add "export" also to the lines echo'ed into .profile
