### ISSUE TITLE
`cobra_prep.c`: `-cpp` flag and filenames with spaces (have solution, need a check)

### ISSUE THREAD

**Issue by yilmazdurmaz** [nimble-code/Cobra#37]
trying to check another problem (I reported moments ago) I accidentally stumbled upon another problem. Hopefuly, I have a solution for this one, but will be better if you check it.

when `-cpp` flag is used, apparently a command is spawned to use `CPP` (set to use `gcc`) within `cobra_prep.c`. If used with filenames including spaces, the command tries to process as if multiple file names are given.

in `cobra_prep.c` line:230, wrapping filename placeholder with quotes will invoke the command with the correct filename.
````
snprintf(buf, n, "%s %s -w -E -x %s \"%s\" > %s",
			    CPP, preproc, lang, f, fnm); 
````

The reason I need you to check is that I am not sure if you spawn this command for a single file or for multiple files. If it uses only a single file name then this fix should be fine

**Comment by nimble-code** [comment]
ok, that's another place to fix -- good point -- will get to it
