### ISSUE TITLE
in `cobra_prim.c` file, line 178, `/../bin` seems to be a left over, or!?

### ISSUE THREAD

**Issue by yilmazdurmaz** [nimble-code/Cobra#38]
there is this line in `cobra_prim.c` file, line 178
````
	{	n += strlen(c_base) + strlen("/../bin") - strlen("$COBRA");
````

This seems to be a left-over and might lead to problems in long run.

It seems it was written with two things in mind:
- binary files would be in `$COBRA/bin` folder
- and rules defined by `$C_BASE` would be under `$COBRA/rules`

currently, there are two (again two) issues with this:
- binaries are under `$COBRA/bin_[mac|cygwin|linux]`. The first issue can be solved by telling users to rename the binary folder for their system to `bin`.
- one can change their rules folder with `$C_BASE` before running Cobra for any reason and then the address for `bin` will not be even pointing to Cobra directory.

If the purpose of this line is to point to `bin` folder for cobra, it needs some changes. Unfortunately, I don't have any proposal about that. Hope you will find one

PS: May I ask a question!? is `nimble-code` a team or a single programmer? I feel overwhelming you right now with these issues :)

**Comment by nimble-code** [comment]
oh that's a good catch!
originally there was just that /bin directory without the extended versions for different platforms
good catch -- i should fix that for sure
don't know how to address the second point - will have to think about that on.

no worries about overwhelming me -- more questions, and more findings, are good to improve the tool.
yes, one person, so no time lost in team meetings - the royal "we" can just do the work!

**Comment by sthagen** [comment]
I appreciate every single person project when it feels good for the person. Just stating that here, as I perceive the fashionable perspective of considering such a „problematic situation“ as missing the point: The heart of creation beats in individual people. Any „we“ may band up together, but that is only one possible route …

@nimble-code Thanks a lot for creating and sharing this unique tool.

**Comment by nimble-code** [comment]
true - many really influential developments were spearheaded by one person (Unix: Ken Thompson, C: Dennis Ritchie, C++: Bjarne Straustrup, Plan9: Rob Pike,   etc. etc.)
