### ISSUE TITLE
Restrict analysis to certain files

### ISSUE THREAD

**Issue by keck-in-space** [nimble-code/Cobra#4]
Is it possible to restrict analysis output to certain files only? There are a lot of library files that are part of the ARM CMSIS standard that cause Cobra to output matches, but that are not relevant for analysis since those files won't be changed. Is there a way to filter the output to only specific files?

**Comment by nimble-code** [comment]
Hi David,
There's no builtin option to filter those warnings, but it would be easy to
postprocess the output with an awk-filter and throw out all the
non-relevant matches.
I guess one could imagine a command line option that sets a prefix for all
file matches that should be ignored. It's a thought.
-g

**Comment by keck-in-space** [comment]
That's true. I'll give awk a try. Thank you!
