### ISSUE TITLE
bad field type 'fct'

### ISSUE THREAD

**Issue by davidskeck** [nimble-code/Cobra#40]
Hello,

I'm getting "bad field type 'fct'" when trying to run the basic ruleset. Any ideas?

**Comment by nimble-code** [comment]
i can reproduce that as well -- will check it out!

**Comment by nimble-code** [comment]
yes, it's a bug I introduced in 3.8. 
the fix:  line 365,369 in cobra_eval.y should be:
	case 'f':	
		if (strcmp(s, "fct") == 0)
		{	return fct_t;
		}
		return (strcmp(s, "fnm")     == 0)?fnm_t:0;
a slip in a small rewrite of that code.  will upload the fix with new version 3.9
thanks for reporting!
