### ISSUE TITLE
`json` command line option question

### ISSUE THREAD

**Issue by davidskeck** [nimble-code/Cobra#41]
Hello,

How is the `json` and `json+` command line option used? I have tried the following, but there is no json file saved.

`cobra -json -f p10 test.c`

**Comment by nimble-code** [comment]
so far, the json format is used by the patterns checks (option -pe) and by the standalone backends 'cwe' and 'find_taint'
it should eventually start working for all outputs from the rule libraries
i am working on revising the rule libraries to use pattern sets better, which could be a big improvement in usability (i.e., you don't lost results once they are printed, but they're available in named sets for later refinement and inspection).  especially the P10 rule set is going to improve quite a bit in the next release (3.9)
