### ISSUE TITLE
Assertion failure on Basic rule set

### ISSUE THREAD

**Issue by keck-in-space** [nimble-code/Cobra#46]
Hello,

I am seeing the following assertion error when running the basic rule set.

```cobra: cobra_lib.c:600: clear_range: Assertion `z->upto > z->from' failed.```

Any ideas what might be the cause?

**Comment by nimble-code** [comment]
thanks for reporting this -- yes, this is an issue I know about in the current release
it will be fixed in the next one -- within a week or so
