### ISSUE TITLE
Multiple input directories CLI

### ISSUE THREAD

**Issue by keck-in-space** [nimble-code/Cobra#5]
Is it possible to provide multiple input directories to Cobra via the command line?

As and example, I'd like to be able to do something like this:
```cobra -v -f basic inc/*.[h] src/*.[c]```

This would allow me to maintain the same directory structure as my project and run Cobra more easily.

It's possible I just don't know the correct syntax and Cobra will already support this.

Thanks.

**Comment by nimble-code** [comment]
yes you can pass any number of arguments on the command line, like you did in the examples
cobra -f basic include/*.h scrc/*.c
when a code archive is very large i sometimes collect all files to read into a single file and use the contents of that file as input:
cobra `listofallfiles`
which then expands to thousands of arguments

**Comment by nimble-code** [comment]
(the backquotes were nicely omitted somehow by the gui but they should be around that listallfiles argument)

**Comment by keck-in-space** [comment]
Thank you!
