### ISSUE TITLE
No output files when using cwe and misra2012 rule sets

### ISSUE THREAD

**Issue by mjeronimo** [nimble-code/Cobra#50]
When using the -json option, there is sometimes and output file created and other times not, depending on the ruleset:

**basic:**        \_Basic\_.txt
**cwe:**          No output file
**p10:**          \_P10.txt   (inconsistent naming, see https://github.com/nimble-code/Cobra/pull/47)
**jpl:**              \_JPL\_.txt
**misra2012:**  No output file

I would expect that all rulesets would output JSON consistently and with a consistent output filename convention.

**Comment by nimble-code** [comment]
true -- I will add the same reporting for cwe and misra2012 for consistency.
thanks for reporting this!

**Comment by nimble-code** [comment]
Actually, for cwe, the individual checkers *cwe_119.cobra ... cwe_805.cobra, all produce their output in individual files.
the toplevel checker cwe.cobra could of course combine all those in a single file _CWE_.txt, and delete the individual ones, but I'm not sure if that would be useful....
also, misra2012 does produce an output file, if any warnings are generated.... so I think it's all consistent
