### ISSUE TITLE
problem with spaces in file/folder names while reading from a file list with "-F"

### ISSUE THREAD

**Issue by yilmazdurmaz** [nimble-code/Cobra#51]
Another problem with spaces. I tried to see if I may find the problem and fix it, but it seems I am still not good at C.

File names are read correctly (`prep_args`) from the file list but only the last part of the name of a file, which is composed of non-space characters, continues deep into the program (so a fully non-spaced path is read correctly). `spaced folder name/spaced file name.c` shortens to `name.c` and gives `cannot open file 'name.c'` error.

I saw that there is a statement in `cobra_prep.c`:

> 	// but the filename may contain spaces
> 	// provided they are escaped with a backslash

I then tried to prefix spaces with backslashes, `spaced\ folder\ name/spaced\ file\ name.c`. But now either there is an infinite loop running with this change or something just gets stuck because program does not ever end. To compare this "never ends" I used a single file with a single char in it so it resolves in a second if the file is read correctly.

YILMAZ

**Comment by nimble-code** [comment]
that's annoying -- I'll check it out!

**Comment by nimble-code** [comment]
In the new version of Cobra, the filename can be preceded by compilation directives
(which is useful especially when the filenames are read from a file with the -F argument).
so what trips this up is when Cobra starts looking for those directives, which are separated from
the filename by a space.....  if the filename has a space, the first part is taken to be a directive,
but only -D, -I, and -U are used - the rest is ignored......
I will refine this somewhat to make sure that the part before the space does at least contain
one dash - following a space -- to make sure it really is a directive....

**Comment by nimble-code** [comment]
Fixed (new source file cobra_prep.c -- but didn't update the executables, so please compile from source)
