### ISSUE TITLE
Iridex Ruleset Question

### ISSUE THREAD

**Issue by keck-in-space** [nimble-code/Cobra#6]
Hello,

Can you tell me more about the iridex ruleset? Is it derived from a standard?

Thanks!

**Comment by nimble-code** [comment]
I defined that standard at the request of Iridex, for their safety critical code development at the time.
The standard is based on the JPL standard that I had developed before, for mission critical flight software development (today an Institutional Standard for all flight software development at JPL).
I believe that in-house sw development at Iridex was later stopped, and this is now outsourced. I do not know if the same standard is still in use there -- probably not.

**Comment by keck-in-space** [comment]
Thanks for the information! That helps. I've been trying to link rationale's for specific rules in code review's recently but it looks like I won't be able to do this with Iridex. Thanks again for the info!
