### ISSUE TITLE
Add binaries under releases instead of in the repo

### ISSUE THREAD

**Issue by ivanperez-keera** [nimble-code/Cobra#63]
It is customary practice not to add your own project's binary executables directly to the repo. There are several reasons for that:

- The repo becomes big.

  Binary files are much bigger than a text change. For example, the cobra executable is somewhere between 315K and 410K depending on the platform. Adding versions of these files to the repo means the repo becomes very big very quickly and harder to handle (git operations take longer).

- The executables become outdated quickly.

  Unless you update the executable with every single commit that modifies the code, your executables are outdated as soon as you commit anything to the repo. If you do keep them up-to-date, then problem number one becomes much worse.

Instead, it's a much better practice to do one or two of the following:
- Use the releases feature of github to attach the executables to releases.

  That way, you are clearly signaling that executables are associated only to releases/baselines.
  
- Have a CI setup build the executables for you with every commit, and publish them as a CI artifact.
  
  The result would be that, every time you push changes to github, you get three executables built for that commit (be it a release commit or a development commit). It also means that you don't need to compile them locally and attach them manually, and that people who don't want to compile the tool can grab a development executable with your latest changes without waiting for an actual release.

EDIT: Remove unnecessary explanation. Formatting & typo correction.

**Comment by nimble-code** [comment]
I believe that I am using the first method -- tagging releases for source+executables
updates to sources after a tagged release should be clearly identifiable
let me know if I missed something there

**Comment by ivanperez-keera** [comment]
> I believe that I am using the first method -- tagging releases for source+executables

Instead of uploading them as files to the repo, it's best to put them here and remove the binary executables from the repo:

<img width="566" alt="release-binaries" src="https://github.com/nimble-code/Cobra/assets/1162320/1f56c2b1-9b7b-4ec8-ba63-be5bc65a5c76">

That way they are clearly associated to the release, people can still download them, but they do not "pollute" the repository.

You can even automate it: https://github.com/marketplace/actions/github-action-publish-binaries

**Comment by ivanperez-keera** [comment]
This page can be found here: https://github.com/nimble-code/Cobra/releases

It's also accessible from Releases on this page: https://github.com/nimble-code/Cobra (for me, this appears on the right column).

**Comment by nimble-code** [comment]
I've followed your suggestions -- let me know if I missed anything though.
tx
