### ISSUE TITLE
Cobra json output reports incorrect version number

### ISSUE THREAD

**Issue by ivanperez-keera** [nimble-code/Cobra#73]
Hi,

We are experiencing a strange issue where the output json files indicate that the Cobra version is 4.2, when it should be 4.8.

I think the problem is here:

https://github.com/nimble-code/Cobra/blob/5af7230ecf29a6c9b46ff1bdd60c5d9e51d032db/src_app/json_convert.c#L181

Maybe this needs to be handled with a CPP variable?

**Comment by nimble-code** [comment]
True -- it's just a printf thing though -- the format generated is compatible with the latest 4.8.
I'll fix it soon.
