### ISSUE TITLE
Documentation seems to be outdated. Much of it was last updated 2 years ago aside from change history

### ISSUE THREAD

**Issue by WuTang94** [nimble-code/Cobra#74]
I've been trying to compile and use the tool on a Ubuntu 24 VM. Unfortunately, I've been running into issues and found that use cases keep returning this error:

error: cannot open ~/.cobra : check tool installation
cobra: reading stdin

**Comment by nimble-code** [comment]
Did you do the configuration step?

**Comment by WuTang94** [comment]
I believe so. I entered this command per the readme:

`cobra -configure $COBRA`

And I got the message "[no option](error: missing argument for '-configure')"

I'm also using a Ubuntu 24 VM

**Comment by nimble-code** [comment]
Dud you define the value for $COBRA?

**Comment by WuTang94** [comment]
Most likely not. The README file did not instruct me to do so.

What should I put down?

**Comment by nimble-code** [comment]
First line of the instructions: the directory where you installed the tool
(full pathname)

**Comment by WuTang94** [comment]
Gotcha, that worked, thanks! It wasn't clear in the instructions that I had to set my clone directory as $COBRA. Namely, I think putting something like "export $COBRA (directory name)" would have helped me, as I'm still only an intermediate Linux user.

**Comment by WuTang94** [comment]
I think I may wind up closing this issue and may make a merge request with proposed updates to the REPO. Thank you for your help!
